proxy:
  title: Open Analytics Shiny Proxy
  port: 8080
  authentication: none
  hide-navbar: true
  admin-groups: admins
  users:
  - name: doug
    password: pass
    groups: admins
  docker:
      internal-networking: true
      container-protocol: http
  specs:
  - id: lemur
    display-name: Life Expectancy Monitor
    description: Life Expectancy Monitor
    container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');library(lemur);lemur::run_app()"]
    container-image: lemur
    container-network: shiny-net
    container-log-path: ./container-logs
logging:
  file:
    shinyproxy.log



