proxy:
  title: Open Analytics Shiny Proxy
  port: 8080
  authentication: none
  hide-navbar: true
  docker:
      internal-networking: true
      container-protocol: http
  specs:
  - id: lemur
    display-name: Life Expectancy Monitor
    description: Life Expectancy Monitor
    container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');library(lemur);lemur::run_app(serverMode=T)"]
    container-image: lemur_shiny
    container-network: lemur_net
    container-log-path: ./container-logs
logging:
  file:
    shinyproxy.log



